version: '3'

services:
  app:
    build:
      context: .
    image: outline-gauth-backend
    container_name: outline-gauth-backend
#    ports:
#      - "5001:5000"
    environment:
      - APP_API_URL=secret # like APP_API_URL=https://1.2.3.4:5678/eskibmyshkibylypchelami
      - APP_API_KEY=secret # like APP_API_KEY=ABCDEFABCDEFABCDEFABCDEF
    restart: always
    networks:
      - app-network

  oauth2_proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.2.1
    container_name: oauth2_proxy
    ports:
      - "4180:4180"
    environment:
      - OAUTH2_PROXY_PROVIDER=google
      - OAUTH2_PROXY_SKIP_PROVIDER_BUTTON=true
      - OAUTH2_PROXY_EMAIL_DOMAINS=exmaple.com,example.org,gosuslugi.ru
      - OAUTH2_PROXY_CLIENT_ID=YOUR_KEY_ID.apps.googleusercontent.com
      - OAUTH2_PROXY_CLIENT_SECRET=YOUR_CLIENT_SECRET
      - OAUTH2_PROXY_COOKIE_SECRET=YOUR_COOKIE_SECRET # you may generate any 16-bit string for this
      - OAUTH2_PROXY_REDIRECT_URL=http://YOUR_PUBLIC_HOSTNAME/oauth2/callback
      - OAUTH2_PROXY_UPSTREAMS=http://app:5000/
      - OAUTH2_PROXY_HTTP_ADDRESS=0.0.0.0:4180
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
